version: "3.7"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d/:ro"
  nginx:
    image: nginx:1.15.11
    container_name: nginx
    user: root
    ports:
      - "80:80"
      - "4433:4433"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "~/certs-dev:/certificates"


        