version: "3.7"

services:
  nginx:
    image: nginx:1.15.11
    container_name: nginx
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./configs/nginx.conf:/etc/nginx/nginx.conf"
      - "~/certificates:/certificates"

        